### ISSUE TITLE
Remove console logs from this extension

### ISSUE THREAD

**Issue by TheAdnan** [TheAdnan/instagram-download#1]
Remove console logs with appropriate return values or anything reasonable.

**Comment by azharakbar** [comment]
Hi,
I will do this ... 
Can you explain me further ... 
Like return values should be of what type ?? 
And where are the values returned by this function handled ??

**Comment by TheAdnan** [comment]
It's these console logs from this file:
[index.js](https://github.com/TheAdnan/instagram-download/blob/master/index.js)

**Comment by oktaysabak** [comment]
add this command to end of file:
console.clear();

**Comment by TheAdnan** [comment]
Good suggestion, [oktaysabak](https://github.com/oktaysabak)!

**Comment by azharakbar** [comment]
Assign it to me
I have created a pull request :)

**Comment by azharakbar** [comment]
Is there anything further .. ??
This is what I understood from your Message .. .
pls. say if anything further to do ...

**Comment by Toyrone** [comment]
Hi, Is there anyway I can contribute to this?

**Comment by TheAdnan** [comment]
@azharakbar I've commented on your pull request, if you have any further questions, ask me there.
@Toyrone yeah mate, maybe porting the extension to chrome, could you do that?

**Comment by azharakbar** [comment]
Is it mergerd ?? is the issue closed ?? 
or is there something else ??
